CREATE TABLE [dbo].[NAK_TEMP_PERSON] (
    [A_ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [A_NATIONALITY]          INT           NULL,
    [A_SKILL]                TEXT          NULL,
    [A_MAINADJUSTINGDATA]    INT           NULL,
    [A_MAINFULLNAME]         VARCHAR (255) NULL,
    [A_DEATHDATE]            DATETIME      NULL,
    [A_NOTE]                 TEXT          NULL,
    [A_MAINFULLNAME_EN]      VARCHAR (255) NULL,
    [A_SKILL_EN]             TEXT          NULL,
    [A_NOTE_EN]              TEXT          NULL,
    [A_NICKNAME_EN]          VARCHAR (255) NULL,
    [A_MAINADJUSTINGDATA_EN] INT           NULL,
    [A_NATIONALITY_EN]       INT           NULL,
    [A_DEATHDATE_EN]         DATETIME      NULL,
    [TS]                     DATETIME      NULL,
    [GUID]                   VARCHAR (255) NULL,
    [type]                   VARCHAR (50)  NULL,
    [A_ISPHOTO]              BIT           NULL,
    [A_ISPHOTO_EN]           BIT           NULL,
    [A_NAKSOURCE]            INT           NULL,
    [A_ISAPROVE]             BIT           NULL,
    [A_BIOGRAPHY]            TEXT          NULL,
    [A_BIOGRAPHY_EN]         TEXT          NULL,
    [A_MARK]                 TEXT          NULL,
    [A_MARK_EN]              TEXT          NULL,
    [A_BIRTHPLACE_EN]        VARCHAR (255) NULL,
    [A_BIRTHPLACE]           VARCHAR (255) NULL,
    [A_SEX]                  INT           NULL,
    [A_SEX_EN]               INT           NULL,
    [A_NICKNAME]             VARCHAR (255) NULL,
    [A_CREATEDATE]           DATETIME      NULL,
    [A_MARITAL_STATUS]       VARCHAR (255) NULL,
    [A_RELIGION]             VARCHAR (255) NULL,
    [A_RELIGION_EN]          VARCHAR (255) NULL,
    [A_MARITAL_STATUS_EN]    VARCHAR (255) NULL,
    [A_CODE]                 VARCHAR (255) NULL,
    [A_DEATHDATENEW]         VARCHAR (255) NULL,
    [A_BDEATHDATE]           DATETIME      NULL,
    [A_CATEGORYPERSON]       INT           NULL,
    CONSTRAINT [PK_NAK_TEMP_PERSON] PRIMARY KEY CLUSTERED ([A_ID] ASC)
);

