SELECT COUNT(wantedInitiator) AS FSB
FROM NAK_TEMP_WANTED_INIT
WHERE CHARINDEX('фсб',wantedInitiator) > 0

SELECT COUNT(DISTINCT wantedInitiator) AS NAME
FROM NAK_TEMP_WANTED_INIT
WHERE CHARINDEX('чеченск',wantedInitiator) > 0

SELECT COUNT(DISTINCT wantedInitiator) AS DistALL
FROM NAK_TEMP_WANTED_INIT

SELECT COUNT(wantedInitiator) AS INITIAL
FROM NAK_TEMP_WANTED_INIT