USE [nak_data]
GO

/****** Object: Table [dbo].[NAK_ADJUSTINGDATA] Script Date: 17.03.2017 10:59:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

TRUNCATE TABLE [dbo].[NAK_ADJUSTINGDATA];

TRUNCATE TABLE [dbo].[NAK_PERSON];

TRUNCATE TABLE [dbo].[NAK_PERSONPHOTO];

TRUNCATE TABLE [dbo].[NAK_PERSONDOCUMENT];

TRUNCATE TABLE [dbo].[NAK_PHOTO];

