SELECT     dbo.NAK_WANTED.A_ID AS A_FROMID, dbo.NAK_SEARCHTYPE.A_ID AS A_TOID
FROM         dbo.NAK_TEMP_WANTEDTYPESEARCH INNER JOIN
                      dbo.NAK_SEARCHTYPE ON dbo.NAK_TEMP_WANTEDTYPESEARCH.searchType = dbo.NAK_SEARCHTYPE.A_NAME INNER JOIN
                      dbo.NAK_PERSON ON dbo.NAK_TEMP_WANTEDTYPESEARCH.Code = dbo.NAK_PERSON.A_CODE INNER JOIN
                      dbo.NAK_WANTED ON dbo.NAK_PERSON.A_ID = dbo.NAK_WANTED.A_PERSON