SELECT     dbo.NAK_ADJUSTINGDATA.A_PERSON AS A_ID
FROM         dbo.NAK_ADJUSTINGDATA INNER JOIN
                      dbo.NAK_ADJUSTINGDATA AS NAK_ADJUSTINGDATA_1 ON dbo.NAK_ADJUSTINGDATA.A_PERSON <> NAK_ADJUSTINGDATA_1.A_PERSON AND 
                      dbo.NAK_ADJUSTINGDATA.A_LASTNAME = NAK_ADJUSTINGDATA_1.A_LASTNAME AND 
                      dbo.NAK_ADJUSTINGDATA.A_FIRSTNAME = NAK_ADJUSTINGDATA_1.A_FIRSTNAME AND 
                      dbo.NAK_ADJUSTINGDATA.A_SECONDNAME1 = NAK_ADJUSTINGDATA_1.A_SECONDNAME1 AND 
                      dbo.NAK_ADJUSTINGDATA.A_MONTHBIRTHDATE = NAK_ADJUSTINGDATA_1.A_MONTHBIRTHDATE AND 
                      dbo.NAK_ADJUSTINGDATA.A_YEARBIRTHDATE = NAK_ADJUSTINGDATA_1.A_YEARBIRTHDATE AND 
                      dbo.NAK_ADJUSTINGDATA.A_DAYBIRTHDATE = NAK_ADJUSTINGDATA_1.A_DAYBIRTHDATE